site_name: coral_pytorch
site_url: http://rasbt.github.io/coral_pytorch
site_author: Sebastian Raschka
site_description: coral_pytorch is a package implementing the CORAL PyTorch utilities.

repo_url: https://github.com/rasbt/coral_pytorch

#include_search: true
#theme: yeti

docs_dir: docs
site_favicon: favicon.ico

theme: bootstrap

markdown_extensions:
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - extra.css

copyright: Copyright &copy; 2020 <a href="http://sebastianraschka.com">Sebastian Raschka</a>
#google_analytics: ['UA-38457794-3', 'rasbt.github.io/pytorch_coral']

nav:
    - Home: index.md
    - Tutorials:
          - MNIST example: tutorials/Working_with_PDB_Structures_in_DataFrames.md
          - Working with MOL2 Structures in DataFrames: tutorials/Working_with_MOL2_Structures_in_DataFrames.md
    - API:
          - biopandas.pdb: api_subpackages/biopandas.pdb.md
          - biopandas.mol2: api_subpackages/biopandas.mol2.md
    - Changelog: CHANGELOG.md
    - Installation: installation.md
    - Contributing: CONTRIBUTING.md
    - Citing: citing.md
